# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 905eec8300614234f83e29fd7b9f56f98da77545cc9bc65be305eb99e388d855978f199ce1c3f1be9f57733d7ae06faa644173e556e1a3d4bb635bd91a2c820a

test:
  secret_key_base: bccd3cb1610b990cab365771aa589db699158b17a99ee98bc6ee80dfef52523994943d48c5f41e847f718d3e4c78ef6ccc12cefc4fb2bb171e18fe72c026b47c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
